export const appConfig = {
  name: 'Quadrilha do Sesc 2026',
  shortName: 'Quadrilha Alunos',
  subtitle: 'Área dos Quadrilheiros',
  professor: 'Professor Júlio Rangel & Professora Marquisa',
  credit: 'Autor do aplicativo: Edy Marques Freelancer',
  author: 'Edy Marques Freelancer',
  storageKey: 'quadrilha-sesc-alunos-progress-v1',
  splashDuration: 4200,
  apiUrl: import.meta.env.VITE_API_URL || 'http://localhost:3332/api/v1',
  rehearsalDays: ['Segunda-feira', 'Quarta-feira'],
  rehearsalTime: '18h às 20h',
  icons: {
    favicon: `${import.meta.env.BASE_URL}icons/app-icon-192.png`,
    splash: `${import.meta.env.BASE_URL}icons/app-icon-512.png`,
    appleTouch: `${import.meta.env.BASE_URL}icons/app-icon-180.png`,
    pwa192: 'icons/app-icon-192.png',
    pwa512: 'icons/app-icon-512.png',
    maskable512: 'icons/app-icon-maskable-512.png',
  },
  colors: {
    theme: '#005ca8',
    background: '#edf8ff',
    gold: '#29a9e8',
    wine: '#005ca8',
  },
} as const
